name: Dbh72

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git remote add space https://Dbh72:$HF_TOKEN@huggingface.co/spaces/Dbh72/giudizi-ai
          git push --force space main
